import os
import sys
import time
import argparse
import logging
import random
import warnings
import shutil
import functools
import pickle
import subprocess
import copy
import math
from collections import OrderedDict
from datetime import datetime, timedelta
from typing import Optional

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import xarray as xr
from tqdm import tqdm

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.distributed as dist
import torch.multiprocessing as mp
import torch.utils.checkpoint as checkpoint
from torch.utils import data
from torch.utils.data.distributed import DistributedSampler
from torch.nn.parallel import DistributedDataParallel as DDP
from tensorboardX import SummaryWriter

# Ignore all FutureWarnings
warnings.simplefilter(action='ignore', category=FutureWarning)

# =============================================================================
# 0. SEEDING & ENV HELPERS
# =============================================================================
def set_random_seed(seed, deterministic=False):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)
    if deterministic:
        torch.backends.cudnn.deterministic = True
        torch.backends.cudnn.benchmark = False

def _pick_backend(backend_arg):
    if backend_arg:
        return backend_arg
    return 'nccl' if torch.cuda.is_available() else 'gloo'

# =============================================================================
# 1. TIMM COMPATIBILITY (Fallbacks if timm is not installed)
# =============================================================================
try:
    from timm.models.layers import DropPath, trunc_normal_
except ImportError:
    print("timm not found, using internal implementations for DropPath and trunc_normal_")
    
    def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
        # Cut & paste from PyTorch official master until it's in a few official releases - RW
        # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
        def norm_cdf(x):
            return (1. + math.erf(x / math.sqrt(2.))) / 2.

        if (mean < a - 2 * std) or (mean > b + 2 * std):
            warnings.warn("mean is more than 2 std from [a, b] in nn.init.trunc_normal_. "
                          "The distribution of values may be incorrect.",
                          stacklevel=2)

        with torch.no_grad():
            # Values are generated by using a truncated uniform distribution and
            # then using the inverse CDF for the normal distribution.
            # Get upper and lower cdf values
            l = norm_cdf((a - mean) / std)
            u = norm_cdf((b - mean) / std)

            # Uniformly fill tensor with values from [l, u], then translate to
            # [2l-1, 2u-1].
            tensor.uniform_(2 * l - 1, 2 * u - 1)

            # Use inverse cdf transform for normal distribution to get truncated
            # standard normal
            tensor.erfinv_()

            # Transform to proper mean, std
            tensor.mul_(std * math.sqrt(2.))
            tensor.add_(mean)

            # Clamp to ensure it's in the proper range
            tensor.clamp_(min=a, max=b)
            return tensor

    class DropPath(nn.Module):
        """Drop paths (Stochastic Depth) per sample  (when applied in main path of residual blocks)."""
        def __init__(self, drop_prob=None):
            super(DropPath, self).__init__()
            self.drop_prob = drop_prob

        def forward(self, x):
            if self.drop_prob == 0. or not self.training:
                return x
            keep_prob = 1 - self.drop_prob
            shape = (x.shape[0],) + (1,) * (x.ndim - 1)  # work with diff dim tensors, not just 2D ConvNets
            random_tensor = keep_prob + torch.rand(shape, dtype=x.dtype, device=x.device)
            random_tensor.floor_()  # binarize
            output = x.div(keep_prob) * random_tensor
            return output

# =============================================================================
# 2. CONFIGURATION
# =============================================================================
class EasyDict(dict):
    """Convenience class that behaves like a dict but allows access with the attribute syntax."""
    def __getattr__(self, name):
        try:
            return self[name]
        except KeyError:
            raise AttributeError(name)

    def __setattr__(self, name, value):
        self[name] = value

    def __delattr__(self, name):
        del self[name]

__C = EasyDict()
cfg = __C
__C.GLOBAL = EasyDict()
__C.GLOBAL.PATH = './'
__C.GLOBAL.DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
__C.GLOBAL.BATCH_SZIE = 1
# Default paths, will be overridden in main
__C.GLOBAL.SEED = 99
__C.GLOBAL.NUM_THREADS = 16

__C.PG_INPUT_PATH = None # To be set in main
__C.PG_OUT_PATH = None   # To be set in main

__C.ERA5_UPPER_LEVELS = ['1000', '925', '850', '700', '600',
                         '500', '400', '300', '250', '200', '150', '100', '50']
__C.ERA5_SURFACE_VARIABLES = ['msl', 'u10', 'v10', 't2m']
__C.ERA5_UPPER_VARIABLES = ['z', 'q', 't', 'u', 'v']

__C.PG = EasyDict()
__C.PG.HORIZON = 24 

__C.PG.TRAIN = EasyDict()
__C.PG.TRAIN.EPOCHS = 100
__C.PG.TRAIN.LR = 2e-5
__C.PG.TRAIN.WEIGHT_DECAY = 3e-6
__C.PG.TRAIN.ACCUMULATION_STEPS = 1
__C.PG.TRAIN.START_TIME = '20230101 00:00:00'
__C.PG.TRAIN.END_TIME = '20251231 00:00:00'
__C.PG.TRAIN.FREQUENCY = '24h'
__C.PG.TRAIN.BATCH_SIZE = 8
__C.PG.TRAIN.UPPER_WEIGHTS = [3.00, 0.60, 1.50, 0.77, 0.54]
__C.PG.TRAIN.SURFACE_WEIGHTS = [1.50, 0.77, 0.66, 3.00]
__C.PG.TRAIN.UPPER_LOSS_WEIGHT = 1.0
__C.PG.TRAIN.SURFACE_LOSS_WEIGHT = 0.25
__C.PG.TRAIN.SAVE_INTERVAL = 1
__C.PG.TRAIN.EARLY_STOP = 20

__C.PG.VAL = EasyDict()
__C.PG.VAL.START_TIME = '20260101 00:00:00'
__C.PG.VAL.END_TIME = '20260331 00:00:00'
__C.PG.VAL.FREQUENCY = '24h'
__C.PG.VAL.BATCH_SIZE = 1
__C.PG.VAL.INTERVAL = 1

__C.PG.TEST = EasyDict()
__C.PG.TEST.START_TIME = '20260401 00:00:00'
__C.PG.TEST.END_TIME = '20260526 00:00:00'
__C.PG.TEST.FREQUENCY = '24h'
__C.PG.TEST.BATCH_SIZE = 1

__C.PG.BENCHMARK = EasyDict()
__C.MODEL = EasyDict()

# =============================================================================
# 3. DISTRIBUTED UTILS
# =============================================================================
def init_dist(launcher, backend='nccl', **kwargs):
    if mp.get_start_method(allow_none=True) is None:
        mp.set_start_method('spawn')
    if launcher == 'pytorch':
        _init_dist_pytorch(backend, **kwargs)
    elif launcher == 'slurm':
        _init_dist_slurm(backend, **kwargs)
    else:
        raise ValueError(f'Invalid launcher type: {launcher}')

def _init_dist_pytorch(backend, **kwargs):
    if 'RANK' not in os.environ or 'WORLD_SIZE' not in os.environ:
        raise RuntimeError(
            'Distributed requested but RANK/WORLD_SIZE not set. '
            'Launch with torchrun (recommended) or set env vars manually.'
        )
    rank = int(os.environ.get('RANK', 0))
    local_rank = int(os.environ.get('LOCAL_RANK', 0))
    num_gpus = torch.cuda.device_count()
    if num_gpus > 0:
        torch.cuda.set_device(local_rank % num_gpus)
    dist.init_process_group(backend=backend, **kwargs)

def _init_dist_slurm(backend, port=None):
    proc_id = int(os.environ['SLURM_PROCID'])
    ntasks = int(os.environ['SLURM_NTASKS'])
    node_list = os.environ['SLURM_NODELIST']
    num_gpus = torch.cuda.device_count()
    if num_gpus > 0:
        torch.cuda.set_device(proc_id % num_gpus)
    addr = subprocess.getoutput(f'scontrol show hostname {node_list} | head -n1')
    if port is not None:
        os.environ['MASTER_PORT'] = str(port)
    elif 'MASTER_PORT' in os.environ:
        pass
    else:
        os.environ['MASTER_PORT'] = '29500'
    os.environ['MASTER_ADDR'] = addr
    os.environ['WORLD_SIZE'] = str(ntasks)
    os.environ['LOCAL_RANK'] = str(proc_id % num_gpus) if num_gpus > 0 else '0'
    os.environ['RANK'] = str(proc_id)
    dist.init_process_group(backend=backend)

def get_dist_info():
    if dist.is_available():
        initialized = dist.is_initialized()
    else:
        initialized = False
    if initialized:
        rank = dist.get_rank()
        world_size = dist.get_world_size()
    else:
        rank = 0
        world_size = 1
    return rank, world_size

def is_dist_ready():
    return dist.is_available() and dist.is_initialized()

def unwrap_model(model):
    return model.module if hasattr(model, 'module') else model

def strip_module_prefix(state_dict):
    return {k.replace('module.', '', 1) if k.startswith('module.') else k: v
            for k, v in state_dict.items()}

def load_model_state(model, checkpoint, strict=True):
    if isinstance(checkpoint, nn.Module):
        state_dict = checkpoint.state_dict()
    else:
        state_dict = checkpoint['model'] if isinstance(checkpoint, dict) and 'model' in checkpoint else checkpoint
    if not hasattr(state_dict, 'items'):
        raise TypeError('Checkpoint must be a state_dict, a dict containing "model", or an nn.Module.')
    unwrap_model(model).load_state_dict(strip_module_prefix(state_dict), strict=strict)

def masked_mean(values, mask):
    mask = mask.to(device=values.device, dtype=values.dtype)
    while mask.dim() < values.dim():
        mask = mask.unsqueeze(0)
    mask = mask.expand_as(values)
    denom = mask.sum().clamp_min(1.0)
    return (values * mask).sum() / denom

def current_learning_rate(optimizer):
    if hasattr(optimizer, 'param_groups') and optimizer.param_groups:
        return optimizer.param_groups[0]['lr']
    inner_optimizer = getattr(optimizer, 'optimizer', None)
    if inner_optimizer is not None and hasattr(inner_optimizer, 'param_groups') and inner_optimizer.param_groups:
        return inner_optimizer.param_groups[0]['lr']
    return 0.0

# =============================================================================
# 4. GENERAL UTILS (Logging, Vis)
# =============================================================================
def logger_info(logger_name, log_path='default_logger.log'):
    log = logging.getLogger(logger_name)
    if log.hasHandlers():
        pass
    else:
        level = logging.INFO
        formatter = logging.Formatter('%(asctime)s.%(msecs)03d : %(message)s', datefmt='%y-%m-%d %H:%M:%S')
        fh = logging.FileHandler(log_path, mode='a')
        fh.setFormatter(formatter)
        log.setLevel(level)
        log.addHandler(fh)
        sh = logging.StreamHandler()
        sh.setFormatter(formatter)
        log.addHandler(sh)

def mkdir(path):
    if not os.path.exists(path):
        os.makedirs(path, exist_ok=True)

def mkdirs(paths):
    if isinstance(paths, str):
        mkdir(paths)
    else:
        for path in paths:
            mkdir(path)

def visuailze(output, target, input, var, z, step, path, mask=None):
    variables = cfg.ERA5_UPPER_VARIABLES
    var_idx = variables.index(var)
    fig = plt.figure(figsize=(16, 2))
    
    if mask is not None:
        mask_bool = mask.detach().cpu().numpy().astype(bool)
        output_masked = np.where(mask_bool, output[var_idx, z, :, :], np.nan)
        target_masked = np.where(mask_bool, target[var_idx, z, :, :], np.nan)
        input_masked = np.where(mask_bool, input[var_idx, z, :, :], np.nan)
        bias_masked = np.where(mask_bool, output[var_idx, z, :, :] - target[var_idx, z, :, :], np.nan)
    else:
        output_masked = output[var_idx, z, :, :]
        target_masked = target[var_idx, z, :, :]
        input_masked = input[var_idx, z, :, :]
        bias_masked = output[var_idx, z, :, :] - target[var_idx, z, :, :]

    ax1 = fig.add_subplot(143)
    plot1 = ax1.imshow(output_masked, cmap="RdBu")
    plt.colorbar(plot1, ax=ax1, fraction=0.05, pad=0.05)
    ax1.title.set_text('pred')

    ax2 = fig.add_subplot(142)
    plot2 = ax2.imshow(target_masked, cmap="RdBu")
    plt.colorbar(plot2, ax=ax2, fraction=0.05, pad=0.05)
    ax2.title.set_text('gt')

    ax3 = fig.add_subplot(141)
    plot3 = ax3.imshow(input_masked, cmap="RdBu")
    plt.colorbar(plot3, ax=ax3, fraction=0.05, pad=0.05)
    ax3.title.set_text('input')

    ax4 = fig.add_subplot(144)
    plot4 = ax4.imshow(bias_masked, cmap="RdBu")
    plt.colorbar(plot4, ax=ax4, fraction=0.05, pad=0.05)
    ax4.title.set_text('bias')

    plt.tight_layout()
    plt.savefig(fname=os.path.join(path, '{}_{}_Z{}'.format(step, variables[var_idx], z)))
    plt.close()

def visuailze_surface(output, target, input, var, step, path, mask=None):
    variables = cfg.ERA5_SURFACE_VARIABLES
    var_idx = variables.index(var)
    fig = plt.figure(figsize=(16, 2))
    
    if mask is not None:
        mask_bool = mask.detach().cpu().numpy().astype(bool)
        output_masked = np.where(mask_bool, output[var_idx, :, :], np.nan)
        target_masked = np.where(mask_bool, target[var_idx, :, :], np.nan)
        input_masked = np.where(mask_bool, input[var_idx, :, :], np.nan)
        bias_masked = np.where(mask_bool, output[var_idx, :, :] - target[var_idx, :, :], np.nan)
    else:
        output_masked = output[var_idx, :, :]
        target_masked = target[var_idx, :, :]
        input_masked = input[var_idx, :, :]
        bias_masked = output[var_idx, :, :] - target[var_idx, :, :]

    ax1 = fig.add_subplot(143)
    plot1 = ax1.imshow(output_masked, cmap="RdBu")
    plt.colorbar(plot1, ax=ax1, fraction=0.05, pad=0.05)
    ax1.title.set_text('pred')

    ax2 = fig.add_subplot(142)
    plot2 = ax2.imshow(target_masked, cmap="RdBu")
    plt.colorbar(plot2, ax=ax2, fraction=0.05, pad=0.05)
    ax2.title.set_text('gt')

    ax3 = fig.add_subplot(141)
    plot3 = ax3.imshow(input_masked, cmap="RdBu")
    plt.colorbar(plot3, ax=ax3, fraction=0.05, pad=0.05)
    ax3.title.set_text('input')

    ax4 = fig.add_subplot(144)
    plot4 = ax4.imshow(bias_masked, cmap="RdBu")
    plt.colorbar(plot4, ax=ax4, fraction=0.05, pad=0.05)
    ax4.title.set_text('bias')

    plt.tight_layout()
    plt.savefig(fname=os.path.join(path, '{}_{}'.format(step, variables[var_idx])))
    plt.close()

def save_errorScores(csv_path, z, q, t, u, v, wind_speed, surface, surface_wind_speed, error):
    # Helper to convert dicts to dataframes and save
    def save_df(data_dict, cols, name):
        if data_dict:
             df = pd.DataFrame.from_dict(data_dict, orient='index', columns=cols)
             df.to_csv("{}/{}.csv".format(csv_path, f'{error}_{name}'))

    save_df(z, cfg.ERA5_UPPER_LEVELS, 'upper_z')
    save_df(q, cfg.ERA5_UPPER_LEVELS, 'upper_q')
    save_df(t, cfg.ERA5_UPPER_LEVELS, 'upper_t')
    save_df(u, cfg.ERA5_UPPER_LEVELS, 'upper_u')
    save_df(v, cfg.ERA5_UPPER_LEVELS, 'upper_v')
    if wind_speed: save_df(wind_speed, cfg.ERA5_UPPER_LEVELS, 'upper_wind_speed')
    save_df(surface, cfg.ERA5_SURFACE_VARIABLES, 'surface')
    if surface_wind_speed: save_df(surface_wind_speed, ['wind_speed'], 'surface_wind_speed')

# =============================================================================
# 5. SCORING UTILS (RMSE, ACC)
# =============================================================================
@torch.jit.script
def lat(j: torch.Tensor, num_lat: int) -> torch.Tensor:
    return 90. - j * 180./float(num_lat-1)

@torch.jit.script
def latitude_weighting_factor_torch(j: torch.Tensor, num_lat: int, s: torch.Tensor) -> torch.Tensor:
    return num_lat * torch.cos(3.1416/180. * lat(j, num_lat))/s

@torch.jit.script
def weighted_rmse_torch_channels(pred: torch.Tensor, target: torch.Tensor, mask: Optional[torch.Tensor] = None) -> torch.Tensor:
    num_lat = pred.shape[-2]
    lat_t = torch.arange(start=0, end=num_lat, device=pred.device)
    s = torch.sum(torch.cos(3.1416/180. * lat(lat_t, num_lat)))

    if pred.dim() == 3:
        weight = torch.reshape(latitude_weighting_factor_torch(lat_t, num_lat, s), (1, -1, 1))
    else:
        weight = torch.reshape(latitude_weighting_factor_torch(lat_t, num_lat, s), (1, 1, -1, 1))

    if mask is not None:
        mask = mask.to(pred.device)
        if pred.dim() == 3:
            mask = mask.unsqueeze(0)
        else:
            mask = mask.unsqueeze(0).unsqueeze(0)
        valid_weights = (weight * mask).sum(dim=(-1, -2))
        squared_error = (pred - target)**2
        weighted_masked_error = weight * mask * squared_error
        result = torch.sqrt(weighted_masked_error.sum(dim=(-1, -2)) / torch.clamp(valid_weights, min=1.0e-12))
    else:
        result = torch.sqrt(torch.mean(weight * (pred - target)**2., dim=(-1, -2)))
    return result

@torch.jit.script
def weighted_acc_torch_channels(pred: torch.Tensor, target: torch.Tensor) -> torch.Tensor:
    num_lat = pred.shape[-2]
    lat_t = torch.arange(start=0, end=num_lat, device=pred.device)
    s = torch.sum(torch.cos(3.1416/180. * lat(lat_t, num_lat)))
    if pred.dim() == 3:
        weight = torch.reshape(latitude_weighting_factor_torch(lat_t, num_lat, s), (1, -1, 1))
    else:
        weight = torch.reshape(latitude_weighting_factor_torch(lat_t, num_lat, s), (1, 1, -1, 1))
    
    numerator = torch.sum(weight * pred * target, dim=(-1, -2))
    denominator = torch.sqrt(torch.sum(weight * pred * pred, dim=(-1, -2)) * torch.sum(weight * target * target, dim=(-1, -2)))
    return numerator / torch.clamp(denominator, min=1.0e-12)

# =============================================================================
# 6. DATA UTILS
# =============================================================================
class NetCDFDataset(data.Dataset):
    """Dataset class for the era5 upper and surface variables."""
    def __init__(self, nc_path, data_transform=None, seed=1234, training=True, validation=False, startDate='20150101', endDate='20150102', freq='H', horizon=24):
        self.horizon = horizon
        self.nc_path = nc_path
        self.training = training
        self.validation = validation
        self.data_transform = data_transform
        # Per-worker file cache: avoids re-opening the same NetCDF file
        # repeatedly within one DataLoader worker process.
        self._nc_cache = {}
        
        pd_freq = freq.upper()
        if training or validation:
            self.keys = list(pd.date_range(start=startDate, end=endDate, freq=pd_freq))
        else:
            self.keys = list(pd.date_range(start=startDate, end=endDate, freq=pd_freq))

        freq_digits = ''.join(filter(str.isdigit, freq))
        freq_int = int(freq_digits) if freq_digits else 1
        if horizon % freq_int != 0:
            raise ValueError(f"Horizon ({horizon}h) must be divisible by frequency ({freq}).")
        horizon_steps = horizon // freq_int
        self.length = len(self.keys) - horizon_steps
        if self.length <= 0:
            raise ValueError(f"Dataset length is non-positive ({self.length}). Check date range and horizon.")
        print(f"{'Train' if training else 'Val/Test'} dataset keys: {len(self.keys)}, Length: {self.length}")
        random.seed(seed)

    def _candidate_paths(self, kind, dt):
        if kind == 'surface':
            prefixes = ['surface']
            subdir = 'surface'
        elif kind == 'upper':
            prefixes = ['upper_air', 'upper']
            subdir = 'upper'
        else:
            raise ValueError(f"Unknown kind: {kind}")

        day_str = datetime.strftime(dt, '%Y_%m_%d')
        month_str = datetime.strftime(dt, '%Y_%m')
        day_compact = datetime.strftime(dt, '%Y%m%d')
        month_compact = datetime.strftime(dt, '%Y%m')
        day_dash = datetime.strftime(dt, '%Y-%m-%d')
        month_dash = datetime.strftime(dt, '%Y-%m')
        base_dir = os.path.join(self.nc_path, subdir)
        search_dirs = [
            base_dir,
            self.nc_path,
            os.path.join(base_dir, datetime.strftime(dt, '%Y')),
            os.path.join(base_dir, datetime.strftime(dt, '%Y'), datetime.strftime(dt, '%m')),
            os.path.join(base_dir, month_compact),
        ]

        patterns = []
        for prefix in prefixes:
            patterns.extend([
                f'{prefix}_{day_str}.nc',
                f'{prefix}_{month_str}.nc',
                f'{prefix}_{day_compact}.nc',
                f'{prefix}_{month_compact}.nc',
                f'{prefix}_{day_dash}.nc',
                f'{prefix}_{month_dash}.nc',
            ])
        patterns.extend([
            f'{day_str}.nc',
            f'{month_str}.nc',
            f'{day_compact}.nc',
            f'{month_compact}.nc',
            f'{day_dash}.nc',
            f'{month_dash}.nc',
        ])

        return [os.path.join(directory, pattern) for directory in search_dirs for pattern in patterns]

    def _open_nc(self, kind, dt):
        """
        Open a NetCDF file, normalise its time coordinate, and return the
        open Dataset.  Results are cached by (kind, date-string) so that the
        same file is never opened more than once per worker process.
        """
        cache_key = (kind, dt.strftime('%Y%m%d'))
        if cache_key in self._nc_cache:
            return self._nc_cache[cache_key]

        # Try daily then monthly naming to support both layouts.
        for path in self._candidate_paths(kind, dt):
            if os.path.exists(path):
                ds = xr.open_dataset(path, decode_timedelta=False)
                # Normalise time coordinate so .isel(time=0) always works.
                # Case 1: named 'valid_time' instead of 'time'
                if 'valid_time' in ds.variables and 'time' not in ds.variables:
                    ds = ds.rename({'valid_time': 'time'})
                # Case 2: 'time' is a dimension but not yet an indexed coordinate
                if 'time' in ds.dims and 'time' not in ds.coords:
                    if 'time' in ds.variables:
                        ds = ds.assign_coords(time=ds['time'])
                    elif 'valid_time' in ds.variables:
                        ds = ds.assign_coords(time=ds['valid_time']).drop_vars('valid_time')
                    else:
                        # 'time' is a bare integer dimension with no coordinate
                        # variable at all (2026 surface files written without
                        # encoding datetime info). Reconstruct from dt.
                        correct_ts = np.array(
                            [np.datetime64(dt.strftime('%Y-%m-%dT%H:%M:%S'), 'ns')]
                        )
                        ds = ds.assign_coords(time=('time', correct_ts))
                # Case 3: both 'time' and 'valid_time' present – drop the redundant one
                if 'time' in ds.coords and 'valid_time' in ds.coords:
                    ds = ds.drop_vars('valid_time')
                # Case 4: 'time' coord exists but has integer dtype, not datetime64
                # (safety net: time variable present but not encoded as datetime)
                if 'time' in ds.coords and not np.issubdtype(ds['time'].dtype, np.datetime64):
                    correct_ts = np.array(
                        [np.datetime64(dt.strftime('%Y-%m-%dT%H:%M:%S'), 'ns')]
                    )
                    ds = ds.assign_coords(time=('time', correct_ts))
                self._nc_cache[cache_key] = ds
                return ds
        tried = ", ".join(self._candidate_paths(kind, dt))
        raise FileNotFoundError(f"No {kind} NetCDF file found for {dt:%Y-%m-%d}. Tried: {tried}")

    def __getstate__(self):
        """Don't pickle cached open datasets across multiprocessing workers."""
        state = self.__dict__.copy()
        state['_nc_cache'] = {}
        return state
    def nctonumpy(self, dataset_upper, dataset_surface):
        # Stack all upper-air variables in one shot — fewer .values calls
        # means fewer NetCDF decompressions and fewer intermediate arrays.
        upper = np.stack(
            [dataset_upper[v].values.astype(np.float32)
             for v in ('z', 'q', 't', 'u', 'v')],
            axis=0
        )  # (5, level, lat, lon)
        upper = upper[:, ::-1, :, :].copy()  # levels in descending order

        surface = np.stack(
            [dataset_surface[v].values.astype(np.float32)
             for v in ('msl', 'u10', 'v10', 't2m')],
            axis=0
        )  # (4, lat, lon)
        return upper, surface

    def LoadData(self, key):
        start_time = key
        start_date_str = datetime.strftime(key, '%Y_%m_%d')
        end_time = key + timedelta(hours=self.horizon)
        end_date_str = datetime.strftime(end_time, '%Y_%m_%d')

        # Open all four datasets (cached after first access in this worker)
        input_surface_dataset  = self._open_nc('surface', start_time)
        input_upper_dataset    = self._open_nc('upper',   start_time)
        target_surface_dataset = self._open_nc('surface', end_time)
        target_upper_dataset   = self._open_nc('upper',   end_time)

        # Each daily file has exactly 1 timestep — use positional selection
        # (.isel) which is O(1), rather than .sel(method='nearest') which
        # scans the coordinate array.
        def _sel_time(ds, dt):
            if 'expver' in ds:
                return ds.sel(expver=5).isel(time=0)
            return ds.isel(time=0)

        inp_surf   = _sel_time(input_surface_dataset,  start_time)
        inp_upper  = _sel_time(input_upper_dataset,    start_time)
        tgt_surf   = _sel_time(target_surface_dataset, end_time)
        tgt_upper  = _sel_time(target_upper_dataset,   end_time)

        inp,    inp_surface = self.nctonumpy(inp_upper,  inp_surf)
        target, tgt_surface = self.nctonumpy(tgt_upper,  tgt_surf)
        return inp, inp_surface, target, tgt_surface, (start_date_str, end_date_str)

    def __getitem__(self, index):
        iii = self.keys[index]
        input, input_surface, target, target_surface, periods = self.LoadData(iii)
        if self.training and self.data_transform is not None:
            input = self.data_transform(input)
            input_surface = self.data_transform(input_surface)
        return input, input_surface, target, target_surface, periods

    def __len__(self):
        return self.length

# Data Helper Functions
def weatherStatistics_input(filepath, device="cpu"):
    surface_mean = np.load(os.path.join(filepath, "surface_mean.npy")).astype(np.float32)
    surface_std = np.load(os.path.join(filepath, "surface_std.npy")).astype(np.float32)
    surface_mean = torch.from_numpy(surface_mean)
    surface_std = torch.from_numpy(surface_std)

    upper_mean = np.load(os.path.join(filepath, "upper_mean.npy")).astype(np.float32)
    upper_std = np.load(os.path.join(filepath, "upper_std.npy")).astype(np.float32)
    upper_mean = torch.from_numpy(upper_mean)
    upper_std = torch.from_numpy(upper_std)

    return surface_mean.to(device), surface_std.to(device), upper_mean.to(device), upper_std.to(device)

def weatherStatistics_output(filepath, device="cpu"):
    surface_mean = np.load(os.path.join(filepath, "surface_mean.npy")).astype(np.float32)
    surface_std = np.load(os.path.join(filepath, "surface_std.npy")).astype(np.float32)
    surface_mean = torch.from_numpy(surface_mean)
    surface_std = torch.from_numpy(surface_std)
    surface_mean = surface_mean.view(1, 4, 1, 1)
    surface_std = surface_std.view(1, 4, 1, 1)

    upper_mean = np.load(os.path.join(filepath, "upper_mean.npy")).astype(np.float32)
    upper_mean = upper_mean[::-1, :, :, :].copy()
    upper_mean = np.transpose(upper_mean, (1, 3, 0, 2))
    upper_mean = torch.from_numpy(upper_mean)

    upper_std = np.load(os.path.join(filepath, "upper_std.npy")).astype(np.float32)
    upper_std = upper_std[::-1, :, :, :].copy()
    upper_std = np.transpose(upper_std, (1, 3, 0, 2))
    upper_std = torch.from_numpy(upper_std)

    return surface_mean.to(device), surface_std.to(device), upper_mean[..., None].to(device), upper_std[..., None].to(device)

def LoadConstantMask3(filepath, device="cpu"):
    mask = np.load(os.path.join(filepath, f"constantMask{cfg.PG.HORIZON}.npy")).astype(np.float32)
    return torch.from_numpy(mask).to(device)

def LoadCustomMask(filepath, device="cpu"):
    p = os.path.join(filepath, "custom_mask.npy")
    if os.path.exists(p):
        mask = np.load(p).astype(np.float32)
        return torch.from_numpy(mask).to(device)
    else:
        return None

def loadConstMask_h(filepath, device="cpu"):
    mask_h = np.load(os.path.join(filepath, "Constant_17_output_0.npy")).astype(np.float32)
    return torch.from_numpy(mask_h).to(device)

def loadVariableWeights(device="cpu"):
    upper_weights = torch.FloatTensor(cfg.PG.TRAIN.UPPER_WEIGHTS).unsqueeze(0).unsqueeze(2).unsqueeze(3).unsqueeze(4)
    surface_weights = torch.FloatTensor(cfg.PG.TRAIN.SURFACE_WEIGHTS).unsqueeze(0).unsqueeze(2).unsqueeze(3)
    upper_loss_weight = torch.tensor(cfg.PG.TRAIN.UPPER_LOSS_WEIGHT, dtype=torch.float32)
    surface_loss_weight = torch.tensor(cfg.PG.TRAIN.SURFACE_LOSS_WEIGHT, dtype=torch.float32)
    return upper_weights.to(device), surface_weights.to(device), upper_loss_weight.to(device), surface_loss_weight.to(device)

def loadAllConstants(device):
    aux_path = os.path.join(cfg.PG_INPUT_PATH, 'aux_data')
    constants = dict()
    constants['weather_statistics'] = weatherStatistics_input(filepath=aux_path, device=device)
    constants['weather_statistics_last'] = weatherStatistics_output(filepath=aux_path, device=device)
    constants['constant_maps'] = LoadConstantMask3(filepath=aux_path, device=device)
    constants['variable_weights'] = loadVariableWeights(device=device)
    constants['const_h'] = loadConstMask_h(filepath=aux_path, device=device)
    constants['custom_mask'] = LoadCustomMask(filepath=aux_path, device=device)
    return constants

def normData(upper, surface, statistics):
    surface_mean, surface_std, upper_mean, upper_std = statistics
    upper = (upper - upper_mean) / upper_std
    surface = (surface - surface_mean) / surface_std
    return upper, surface

def normBackData(upper, surface, statistics):
    surface_mean, surface_std, upper_mean, upper_std = statistics
    upper = upper * upper_std + upper_mean
    surface = surface * surface_std + surface_mean
    return upper, surface

# =============================================================================
# 7. MODEL LAYERS
# =============================================================================
class PatchEmbedding_pretrain(nn.Module):
    def __init__(self, patch_size, dim):
        super(PatchEmbedding_pretrain, self).__init__()
        self.conv = nn.Conv1d(in_channels=192, out_channels=dim, kernel_size=1, stride=1)
        self.conv_surface = nn.Conv1d(in_channels=112, out_channels=dim, kernel_size=1, stride=1)
        self.window_size = (2, 6, 12)

    def check_image_size_2d(self, x):
        _, _, h, w = x.size()
        mod_pad_w = (self.window_size[2] - w % self.window_size[2]) % self.window_size[2]
        x = F.pad(x, (0, mod_pad_w, 0, 3), 'constant')
        return x

    def check_image_size_3d(self, x):
        _, _, d, h, w = x.size()
        x = F.pad(x, (0, 0, 0, 3, 0, 1), 'constant')
        return x

    def forward(self, input, input_surface, statistics, maps, const_h):
        self.surface_mean, self.surface_std, self.upper_mean, self.upper_std = statistics[0], statistics[1], statistics[2], statistics[3]
        self.constant_masks = maps

        input_surface = input_surface.reshape(input_surface.shape[0], input_surface.shape[1], 1, input_surface.shape[-2], input_surface.shape[-1])
        input_surface = torch.permute(input_surface, (0, 2, 3, 4, 1))
        input_surface = (input_surface - self.surface_mean) / self.surface_std
        input_surface = torch.permute(input_surface, (0, 4, 1, 2, 3))
        input_surface = input_surface.view(input_surface.shape[0], input_surface.shape[1], input_surface.shape[-2], input_surface.shape[-1])
        input_surface = self.check_image_size_2d(input_surface)
        batch_size = input_surface.shape[0]
        input_surface = torch.cat((input_surface, self.constant_masks.expand(batch_size, -1, -1, -1)), dim=1)
        input_surface = input_surface.view(input_surface.shape[0], input_surface.shape[1], input_surface.shape[-2] // 4, 4, input_surface.shape[-1] // 4, 4)
        input_surface = torch.permute(input_surface, (0, 1, 3, 5, 2, 4))
        input_surface = input_surface.reshape(input_surface.shape[0], input_surface.shape[1] * input_surface.shape[2] * input_surface.shape[3], -1)
        input_surface = self.conv_surface(input_surface)
        input_surface = input_surface.view(input_surface.shape[0], input_surface.shape[1], 1, 181, 360)

        input = input.reshape(input.shape[0], input.shape[1], 1, input.shape[2], input.shape[-2], input.shape[-1])
        input = torch.permute(input, (0, 2, 3, 4, 5, 1))
        input = torch.flip(input, [2])
        input = (input - self.upper_mean) / self.upper_std
        input = torch.permute(input, (0, 5, 1, 2, 3, 4))
        input = torch.flip(input, [3])
        input = torch.cat((input, const_h.expand(batch_size, -1, -1, -1, -1, -1)), dim=1)
        input = input.reshape(input.shape[0], input.shape[1], input.shape[3], input.shape[-2], input.shape[-1])
        input = self.check_image_size_3d(input)
        input = input.reshape(input.shape[0], input.shape[1], input.shape[2] // 2, 2, input.shape[-2] // 4, 4, input.shape[-1] // 4, 4)
        input = input.permute(0, 1, 3, 5, 7, 2, 4, 6)
        input = input.reshape(input.shape[0], input.shape[1] * input.shape[2] * input.shape[3] * input.shape[4], -1)
        input = self.conv(input)
        input = input.view(input.shape[0], input.shape[1], 7, 181, 360)

        x = torch.cat((input_surface, input), dim=2)
        x = x.view(x.shape[0], x.shape[1], -1)
        x = torch.permute(x, (0, 2, 1))
        return x

class Mlp(nn.Module):
    def __init__(self, dim, dropout_rate):
        super().__init__()
        self.linear1 = nn.Linear(dim, dim * 4)
        self.linear2 = nn.Linear(dim * 4, dim)
        self.activation = nn.GELU()
        self.drop = nn.Dropout(dropout_rate)

    def forward(self, x):
        x = self.linear1(x)
        x = self.activation(x)
        x = self.drop(x)
        x = self.linear2(x)
        x = self.drop(x)
        return x

class EarthAttention3D(nn.Module):
    def __init__(self, dim, heads, dropout_rate, window_size, device):
        super(EarthAttention3D, self).__init__()
        self.device = device
        self.linear1 = nn.Linear(dim, dim*3, bias=True)
        self.linear2 = nn.Linear(dim, dim)
        self.softmax = nn.Softmax(dim=-1)
        self.dropout = nn.Dropout(dropout_rate)
        self.head_number = heads
        self.dim = dim
        self.scale = (dim//heads)**-0.5
        self.window_size = window_size
        if self.dim == 192: input_shape = [8, 186]
        elif self.dim == 384: input_shape = [8, 96]
        self.type_of_windows = (input_shape[0]//window_size[0])*(input_shape[1]//window_size[1])
        self.earth_specific_bias = torch.zeros(1, self.type_of_windows, heads,
                                               window_size[0] * window_size[1] * window_size[2],
                                               window_size[0] * window_size[1] * window_size[2]).to(self.device)
        self.earth_specific_bias = nn.Parameter(self.earth_specific_bias)
        trunc_normal_(self.earth_specific_bias, std=0.02)
        self._construct_index()

    def _construct_index(self):
        coords_zi = torch.arange(self.window_size[0]).to(self.device)
        coords_zj = -torch.arange(self.window_size[0]).to(self.device)*self.window_size[0]
        coords_hi = torch.arange(self.window_size[1]).to(self.device)
        coords_hj = -torch.arange(self.window_size[1]).to(self.device)*self.window_size[1]
        coords_w = torch.arange(self.window_size[2]).to(self.device)
        coords_1 = torch.stack(torch.meshgrid([coords_zi, coords_hi, coords_w], indexing='ij'))
        coords_2 = torch.stack(torch.meshgrid([coords_zj, coords_hj, coords_w], indexing='ij'))
        coords_flatten_1 = torch.flatten(coords_1, start_dim=1)
        coords_flatten_2 = torch.flatten(coords_2, start_dim=1)
        coords = coords_flatten_1[:, :, None] - coords_flatten_2[:, None, :]
        coords = torch.permute(coords, (1, 2, 0))
        coords[:, :, 2] += self.window_size[2] - 1
        coords[:, :, 1] *= 2 * self.window_size[2] - 1
        coords[:, :, 0] *= (2 * self.window_size[2] - 1) * self.window_size[1]*self.window_size[1]
        self.position_index = torch.sum(coords, dim=-1)
        self.position_index = torch.flatten(self.position_index)

    def forward(self, x, mask):
        original_shape = x.shape
        x = self.linear1(x)
        qkv = torch.reshape(x, shape=(x.shape[0], x.shape[1], x.shape[2], 3, self.head_number, self.dim // self.head_number))
        qkv = torch.permute(qkv, (3, 0, 1, 4, 2, 5))
        query, key, value = qkv[0], qkv[1], qkv[2]
        query = query * self.scale
        attention = (query @ key.transpose(-2, -1))
        EarthSpecificBias = self.earth_specific_bias
        attention = attention + EarthSpecificBias
        if mask is not None:
            nW = mask.shape[0]
            B = attention.shape[0] // nW
            attention = attention.view(B, nW, self.type_of_windows, self.head_number, 
                                       self.window_size[0]*self.window_size[1]*self.window_size[2], 
                                       self.window_size[0]*self.window_size[1]*self.window_size[2]) + mask.unsqueeze(2).unsqueeze(0)
            attention = attention.reshape(B*nW, self.type_of_windows, self.head_number,
                                          self.window_size[0]*self.window_size[1]*self.window_size[2], 
                                          self.window_size[0]*self.window_size[1]*self.window_size[2])
        attention = self.softmax(attention)
        attention = self.dropout(attention)
        x = attention @ value
        x = torch.permute(x, (0, 1, 3, 2, 4))
        x = torch.reshape(x, shape=original_shape)
        x = self.linear2(x)
        x = self.dropout(x)
        return x

class EarthSpecificBlock(nn.Module):
    def __init__(self, dim, drop_path_ratio, heads, device):
        super(EarthSpecificBlock, self).__init__()
        self.device = device
        self.window_size = (2, 6, 12)
        self.drop_path = DropPath(drop_path_ratio) if drop_path_ratio > 0. else nn.Identity()
        self.norm1 = nn.LayerNorm(dim)
        self.norm2 = nn.LayerNorm(dim)
        self.linear = Mlp(dim, 0)
        self.attention = EarthAttention3D(dim, heads, 0, self.window_size, device=self.device)
        self.padding_front, self.padding_back = 0, 5
        if dim == 192: input_shape = [8, 186]
        elif dim == 384: input_shape = [8, 96]
        self.type_of_windows = (input_shape[0]//self.window_size[0])*(input_shape[1]//self.window_size[1])

    def gen_mask(self, x):
        img_mask = torch.zeros((1, x.shape[1], x.shape[2], x.shape[3], 1)).to(self.device)
        mB, mZ, mH, mW, mC = img_mask.shape
        cnt = 0
        z_slices = (slice(0, -self.window_size[0]), slice(-self.window_size[0], -self.window_size[0] // 2), slice(-self.window_size[0] // 2, None))
        h_slices = (slice(0, -self.window_size[1]), slice(self.window_size[1], -self.window_size[1] // 2), slice(-self.window_size[1] // 2, None))
        for z in z_slices:
            for h in h_slices:
                img_mask[:, z, h, :, :] = cnt
                cnt += 1
        img_mask = img_mask.reshape(1, mZ // self.window_size[0], self.window_size[0], mH // self.window_size[1],
                                    self.window_size[1], mW // self.window_size[2], self.window_size[2], 1)
        img_mask = torch.permute(img_mask, (0, 5, 1, 3, 2, 4, 6, 7))
        mask_windows = img_mask.reshape(-1, self.type_of_windows, self.window_size[0], self.window_size[1], self.window_size[2], 1)
        mask_windows = mask_windows.view(-1, self.type_of_windows, self.window_size[0] * self.window_size[1] * self.window_size[2])
        attn_mask = mask_windows.unsqueeze(2) - mask_windows.unsqueeze(3)
        attn_mask = attn_mask.masked_fill(attn_mask != 0, float(-100.0)).masked_fill(attn_mask == 0, float(0.0))
        return attn_mask

    def forward(self, x, Z, H, W, roll):
        shortcut = x
        x = x.view(x.shape[0], Z, H, W, x.shape[2])
        x = F.pad(x, (0, 0, 0, 0, self.padding_front, self.padding_back), 'constant')
        ori_shape = x.shape
        if roll:
            x = torch.roll(x, shifts=[-self.window_size[0]//2, -self.window_size[1]//2, -self.window_size[2]//2], dims=(1, 2, 3))
            mask = self.gen_mask(x)
        else:
            mask = None

        x_window = x.view(x.shape[0], x.shape[1]//self.window_size[0], self.window_size[0], x.shape[2] // self.window_size[1], self.window_size[1], x.shape[3] // self.window_size[2], self.window_size[2], x.shape[-1])
        x_window = torch.permute(x_window, (0, 5, 1, 3, 2, 4, 6, 7))
        x_window = x_window.reshape(x_window.shape[0] * x_window.shape[1], x_window.shape[2]*x_window.shape[3], x_window.shape[4], x_window.shape[5], x_window.shape[6], x_window.shape[7])
        x_window = x_window.contiguous().view(x_window.shape[0], x_window.shape[1], self.window_size[0]*self.window_size[1]*self.window_size[2], x_window.shape[-1])
        attn_windows = self.attention(x_window, mask)
        x_shifted = attn_windows.view(1, attn_windows.shape[0], Z // self.window_size[0], H // self.window_size[1] + 1, self.window_size[0], self.window_size[1], self.window_size[2], -1)
        x_shifted = torch.permute(x_shifted, (0, 2, 4, 3, 5, 1, 6, 7))
        x_shifted = x_shifted.contiguous().view(ori_shape)
        if roll:
            x = torch.roll(x_shifted, shifts=[self.window_size[0]//2, self.window_size[1]//2, self.window_size[2]//2], dims=(1, 2, 3))
        else:
            x = x_shifted
        depth_slice = slice(self.padding_front, x.shape[2] - self.padding_back)
        x = x[:, :, depth_slice, :, :]
        x = x.contiguous().view(x.shape[0], x.shape[1]*x.shape[2]*x.shape[3], x.shape[4])
        x = shortcut + self.drop_path(self.norm1(x))
        x = x + self.drop_path(self.norm2(self.linear(x)))
        return x

class EarthSpecificLayer(nn.Module):
    def __init__(self, depth, dim, drop_path_ratio_list, heads, use_checkpoint, device):
        super(EarthSpecificLayer, self).__init__()
        self.device = device
        self.depth = depth
        block_list = OrderedDict()
        for i_layer in range(depth):
            block_list['EarthSpecificBlock{}'.format(i_layer)] = EarthSpecificBlock(dim, drop_path_ratio_list[i_layer], heads, device=self.device)
        self.blocks = nn.Sequential(block_list)
        self.use_checkpoint = use_checkpoint

    def forward(self, x, Z, H, W):
        i = -1
        for blk in self.blocks:
            i += 1
            if self.use_checkpoint:
                if i % 2 == 0: x = checkpoint.checkpoint(blk, x, Z, H, W, False, use_reentrant=False)
                else: x = checkpoint.checkpoint(blk, x, Z, H, W, True, use_reentrant=False)
            else:
                if i % 2 == 0: x = blk(x, Z, H, W, roll=False)
                else: x = blk(x, Z, H, W, roll=True)
        return x

class DownSample(nn.Module):
    def __init__(self, dim):
        super().__init__()
        self.linear = nn.Linear(in_features=4*dim, out_features=2*dim, bias=False)
        self.norm = nn.LayerNorm(4*dim)

    def forward(self, x, Z, H, W):
        x = x.view(x.shape[0], Z, H, W, x.shape[-1])
        x = F.pad(x, (0, 0, 0, 0, 0, 1), 'constant')
        Z, H, W = x.shape[1], x.shape[2], x.shape[3]
        x = x.view(x.shape[0], Z, H//2, 2, W//2, 2, x.shape[-1])
        x = torch.permute(x, (0, 1, 2, 4, 3, 5, 6))
        x = x.reshape(x.shape[0], Z*(H//2)*(W//2), 4 * x.shape[-1])
        x = self.norm(x)
        x = self.linear(x)
        return x

class UpSample(nn.Module):
    def __init__(self, input_dim, output_dim):
        super().__init__()
        self.linear1 = nn.Linear(input_dim, output_dim*4, bias=False)
        self.linear2 = nn.Linear(output_dim, output_dim, bias=False)
        self.norm = nn.LayerNorm(output_dim)

    def forward(self, x):
        x = self.linear1(x)
        x = x.view(x.shape[0], 8, 91, 180, 2, 2, x.shape[-1]//4)
        x = torch.permute(x, (0, 1, 2, 4, 3, 5, 6))
        x = x.contiguous().view(x.shape[0], 8, 182, 360, x.shape[-1])
        depth_slice = slice(0, x.shape[2]-1)
        x = x[:, :, depth_slice, :, :]
        x = x.reshape(x.shape[0], x.shape[1]*x.shape[2] * x.shape[3], x.shape[-1])
        x = self.norm(x)
        x = self.linear2(x)
        return x

class PatchRecovery_pretrain(nn.Module):
    def __init__(self, dim):
        super().__init__()
        self.patch_size = (2, 4, 4)
        self.dim = dim
        self.conv = nn.Conv1d(in_channels=dim, out_channels=160, kernel_size=1, stride=1)
        self.conv_surface = nn.Conv1d(in_channels=dim, out_channels=64, kernel_size=1, stride=1)

    def forward(self, x, Z, H, W):
        x = torch.permute(x, (0, 2, 1))
        x = x.view(x.shape[0], x.shape[1], Z, H, W)
        output = x[:, :, 1:, :, :]
        output = output.view(output.shape[0], output.shape[1], -1)
        output = self.conv(output)
        output = output.reshape(output.shape[0], 5, self.patch_size[0], self.patch_size[1], self.patch_size[2], Z - 1, H, W)
        output = torch.permute(output, (0, 1, 5, 2, 6, 3, 7, 4))
        output = output.reshape(output.shape[0], 5, 14, 724, 1440)
        depth_slice = slice(0, output.shape[-3] - 1)
        height_slice = slice(0, output.shape[-2] - 3)
        output = output[:, :, depth_slice, height_slice, :]
        output = output.view(output.shape[0], 5, 13, 721, 1440)

        output_surface = x[:, :, 0, :, :]
        output_surface = output_surface.view(output_surface.shape[0], self.dim, -1)
        output_surface = self.conv_surface(output_surface)
        output_surface = output_surface.view(output_surface.shape[0], 4, self.patch_size[1], self.patch_size[2], H, W)
        output_surface = torch.permute(output_surface, (0, 1, 4, 2, 5, 3))
        output_surface = output_surface.reshape(output_surface.shape[0], 4, 724, 1440)
        output_surface = output_surface[:, :, height_slice, :]
        output_surface = output_surface.view(output_surface.shape[0], 4, 721, 1440)
        return output, output_surface

# =============================================================================
# 8. PANGU MODEL
# =============================================================================
class PanguModel(nn.Module):
    def __init__(self, depths=[2, 6, 6, 2], num_heads=[6, 12, 12, 6], dims=[192, 384, 384, 192], patch_size=(2, 4, 4), device=None):
        super(PanguModel, self).__init__()
        self.device = device
        self._input_layer = PatchEmbedding_pretrain(patch_size, dims[0])
        self.downsample = DownSample(dims[0])
        dpr = [x.item() for x in torch.linspace(0, 0.2, sum(depths))]
        self.num_layers = len(depths)
        layer_list = OrderedDict()
        for i_layer in range(self.num_layers):
            layer_list['EarthSpecificLayer{}'.format(i_layer)] = EarthSpecificLayer(
                depth=depths[i_layer],
                dim=dims[i_layer],
                drop_path_ratio_list=dpr[sum(depths[:i_layer]):sum(depths[:i_layer + 1])],
                heads=num_heads[i_layer],
                use_checkpoint=self.training,
                device=self.device)
        self.layers = nn.Sequential(layer_list)
        self.upsample = UpSample(dims[-2], dims[-1])
        self._output_layer = PatchRecovery_pretrain(dims[-2])
        self.apply(self._init_weights)

    def _init_weights(self, m):
        if isinstance(m, nn.Linear):
            trunc_normal_(m.weight, std=.02)
            if m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, nn.LayerNorm):
            nn.init.constant_(m.bias, 0)
            nn.init.constant_(m.weight, 1.0)

    def forward(self, input, input_surface, statistics, maps, const_h):
        x = self._input_layer(input, input_surface, statistics, maps, const_h)
        x = self.layers[0](x, 8, 181, 360)
        skip = x
        x = self.downsample(x, 8, 181, 360)
        x = self.layers[1](x, 8, 91, 180)
        x = self.layers[2](x, 8, 91, 180)
        x = self.upsample(x)
        x = self.layers[3](x, 8, 181, 360)
        x = torch.cat((skip, x), dim=-1)
        output, output_surface = self._output_layer(x, 8, 181, 360)
        return output, output_surface

# =============================================================================
# 9. TRAIN & TEST LOGIC
# finetune
# =============================================================================
def get_all_variables(output_surface, target_surface, output, target):
    """
    Extracts all individual variables from the Surface and Upper-Air tensors.
    
    Surface Channels (4):  0=MSLP, 1=U10, 2=V10, 3=T2M
    Upper Channels (5):    0=Z, 1=Q, 2=T, 3=U, 4=V
    """
    
    # --- SURFACE VARIABLES ---
    # Shape: (Batch, Channel, Lat, Lon)
    
    # 1. MSLP (Mean Sea Level Pressure) - Channel 0
    pred_mslp = output_surface[:, 0, :, :]
    true_mslp = target_surface[:, 0, :, :]
    
    # 2. U10 (10m U-Wind) - Channel 1
    pred_u10 = output_surface[:, 1, :, :]
    true_u10 = target_surface[:, 1, :, :]
    
    # 3. V10 (10m V-Wind) - Channel 2
    pred_v10 = output_surface[:, 2, :, :]
    true_v10 = target_surface[:, 2, :, :]
    
    # 4. T2M (2m Temperature) - Channel 3
    pred_t2m = output_surface[:, 3, :, :]
    true_t2m = target_surface[:, 3, :, :]
    
    # --- UPPER AIR VARIABLES ---
    # Shape: (Batch, Channel, Depth, Lat, Lon)
    
    # 5. Z (Geopotential) - Channel 0
    pred_z = output[:, 0, :, :, :]
    true_z = target[:, 0, :, :, :]
    
    # 6. Q (Specific Humidity) - Channel 1
    pred_q = output[:, 1, :, :, :]
    true_q = target[:, 1, :, :, :]
    
    # 7. T (Temperature) - Channel 2
    pred_t = output[:, 2, :, :, :]
    true_t = target[:, 2, :, :, :]
    
    # 8. U (U-Wind) - Channel 3
    pred_u = output[:, 3, :, :, :]
    true_u = target[:, 3, :, :, :]
    
    # 9. V (V-Wind) - Channel 4
    pred_v = output[:, 4, :, :, :]
    true_v = target[:, 4, :, :, :]
    
    # Optional: Calculate Wind Speeds as well (Derived)
    pred_ws_10 = torch.sqrt(pred_u10**2 + pred_v10**2)
    true_ws_10 = torch.sqrt(true_u10**2 + true_v10**2)
    pred_ws_upper = torch.sqrt(pred_u**2 + pred_v**2)
    true_ws_upper = torch.sqrt(true_u**2 + true_v**2)

    # Return a dictionary for easy access
    return {
        # Surface
        "mslp": (pred_mslp, true_mslp),
        "u10":  (pred_u10, true_u10),
        "v10":  (pred_v10, true_v10),
        "t2m":  (pred_t2m, true_t2m),
        "ws10": (pred_ws_10, true_ws_10),
        
        # Upper Air
        "z": (pred_z, true_z),
        "q": (pred_q, true_q),
        "t": (pred_t, true_t),
        "u": (pred_u, true_u),
        "v": (pred_v, true_v),
        "ws_upper": (pred_ws_upper, true_ws_upper)
    }

def train(model, train_loader, val_loader, optimizer, lr_scheduler, res_path, device, writer, logger, start_epoch,
        rank=0, visualize=False, only_use_wind_speed_loss=False, use_custom_mask=False, use_deepspeed=False,
        train_sampler=None):
    criterion = nn.L1Loss(reduction='none')
    epochs = cfg.PG.TRAIN.EPOCHS
    accumulation_steps = max(1, int(cfg.PG.TRAIN.ACCUMULATION_STEPS))
    if len(train_loader) == 0:
        raise ValueError('Training DataLoader is empty. Check dataset dates, batch size, and drop_last settings.')
    if len(val_loader) == 0:
        raise ValueError('Validation DataLoader is empty. Check validation dates and batch size.')
    best_loss = float('inf')
    epochs_since_last_improvement = 0

    aux_constants = loadAllConstants(device=device)
    upper_weights, surface_weights, upper_loss_weight, surface_loss_weight = aux_constants['variable_weights']

    mask = None
    if use_custom_mask:
        mask = aux_constants['custom_mask']
        if mask is None:
            raise ValueError('Custom mask requested but aux_data/custom_mask.npy was not found.')
        mask_float = (mask != 0).float()
        valid_points = mask_float.sum()
        if valid_points.item() <= 0:
            raise ValueError('Custom mask requested but aux_data/custom_mask.npy has no valid points.')

    for i in range(start_epoch, epochs + 1):
        should_stop = False
        if train_sampler is not None:
            train_sampler.set_epoch(i)
        model.train()
        epoch_loss = 0.0
        epoch_start = time.time()
        total_train_batches = len(train_loader)

        for iter_num, train_data in enumerate(tqdm(train_loader, desc=f'Training epoch {i} rank {rank}')):
            if not use_deepspeed and iter_num % accumulation_steps == 0:
                optimizer.zero_grad(set_to_none=True)

            input, input_surface, target, target_surface, periods = train_data
            input, input_surface, target, target_surface = input.to(device), input_surface.to(device), target.to(device), target_surface.to(device)

            output, output_surface = model(input, input_surface, aux_constants['weather_statistics'],
                                           aux_constants['constant_maps'], aux_constants['const_h'])

            target, target_surface = normData(target, target_surface, aux_constants['weather_statistics_last'])
            
            # --- UPDATED LOSS LOGIC ---
            # Extract all variables for flexible loss calculation
            # finetune
            vars = get_all_variables(output_surface, target_surface, output, target)
            
            if only_use_wind_speed_loss:
                # Use the pre-calculated wind speeds from our new dictionary
                # ws10 is tuple (pred, true)
                surface_wind_speed_loss = criterion(vars['ws10'][0], vars['ws10'][1])
                wind_speed_loss = criterion(vars['ws_upper'][0], vars['ws_upper'][1])
                
                if use_custom_mask:
                    surface_wind_speed_loss = masked_mean(surface_wind_speed_loss, mask_float)
                    wind_speed_loss = masked_mean(wind_speed_loss, mask_float)
                    loss = surface_wind_speed_loss + wind_speed_loss
                else:
                    loss = torch.mean(surface_wind_speed_loss) + torch.mean(wind_speed_loss)
            else:
                # Standard Loss Calculation (Weighted Sum)
                loss_surface = criterion(output_surface, target_surface)
                loss_upper = criterion(output, target)
                
                if use_custom_mask:
                    weighted_surface_loss = masked_mean(loss_surface * surface_weights, mask_float)
                    weighted_upper_loss = masked_mean(loss_upper * upper_weights, mask_float)
                else:
                    weighted_surface_loss = torch.mean(loss_surface * surface_weights)
                    weighted_upper_loss = torch.mean(loss_upper * upper_weights)
                loss = weighted_upper_loss * upper_loss_weight + weighted_surface_loss * surface_loss_weight

            if use_deepspeed:
                model.backward(loss)
                model.step()
            else:
                window_start = (iter_num // accumulation_steps) * accumulation_steps
                window_size = min(accumulation_steps, total_train_batches - window_start)
                (loss / window_size).backward()
                if (iter_num + 1) % accumulation_steps == 0 or (iter_num + 1) == total_train_batches:
                    optimizer.step()
            
            epoch_loss += loss.item()
                
        epoch_loss /= total_train_batches
        torch.cuda.empty_cache()
        epoch_end = time.time()
        current_lr = current_learning_rate(optimizer)
        logger.info("Epoch {} Rank {}: lr={:.6f}, loss={:.6f}, time={:.3f}".format(i, rank, current_lr, epoch_loss, epoch_end-epoch_start))
        
        lr_scheduler.step()
        del input, input_surface, target, target_surface, output, output_surface
        torch.cuda.empty_cache()

        if rank == 0:
            model_save_path = os.path.join(res_path, 'models')
            mkdir(model_save_path)
            if i % cfg.PG.TRAIN.SAVE_INTERVAL == 0:
                save_file = {"model": unwrap_model(model).state_dict(),
                             "optimizer": optimizer.state_dict(),
                             "lr_scheduler": lr_scheduler.state_dict(),
                             "epoch": i}
                torch.save(save_file, os.path.join(model_save_path, 'train_{}.pth'.format(i)))
                logger.info(f"model is saved at {i} epoch.")

            if i % cfg.PG.VAL.INTERVAL == 0:
                with torch.no_grad():
                    model.eval()
                    val_loss = 0.0
                    for val_data in tqdm(val_loader, desc='Validating'):
                        input_val, input_surface_val, target_val, target_surface_val, periods_val = val_data
                        input_val, input_surface_val, target_val, target_surface_val = input_val.to(device), input_surface_val.to(device), target_val.to(device), target_surface_val.to(device)

                        output_val, output_surface_val = model(input_val, input_surface_val,
                                                               aux_constants['weather_statistics'],
                                                               aux_constants['constant_maps'], aux_constants['const_h'])
                        target_val, target_surface_val = normData(target_val, target_surface_val, aux_constants['weather_statistics_last'])

                        # Get variables for validation too
                        vars_val = get_all_variables(output_surface_val, target_surface_val, output_val, target_val)

                        if only_use_wind_speed_loss:
                            if use_custom_mask:
                                surface_wind_speed_loss = masked_mean(criterion(vars_val['ws10'][0], vars_val['ws10'][1]), mask_float)
                                wind_speed_loss = masked_mean(criterion(vars_val['ws_upper'][0], vars_val['ws_upper'][1]), mask_float)
                                loss = surface_wind_speed_loss + wind_speed_loss
                            else:
                                loss = torch.mean(criterion(vars_val['ws10'][0], vars_val['ws10'][1])) + torch.mean(criterion(vars_val['ws_upper'][0], vars_val['ws_upper'][1]))
                        else:
                            val_loss_surface = criterion(output_surface_val, target_surface_val)
                            val_loss_upper = criterion(output_val, target_val)

                            if use_custom_mask:
                                weighted_val_loss_surface = masked_mean(val_loss_surface * surface_weights, mask_float)
                                weighted_val_loss_upper = masked_mean(val_loss_upper * upper_weights, mask_float)
                            else:
                                weighted_val_loss_surface = torch.mean(val_loss_surface * surface_weights)
                                weighted_val_loss_upper = torch.mean(val_loss_upper * upper_weights)
                            loss = weighted_val_loss_upper * upper_loss_weight + weighted_val_loss_surface * surface_loss_weight

                        val_loss += loss.item()

                    val_loss /= len(val_loader)
                    writer.add_scalars('Loss', {'train': epoch_loss, 'val': val_loss}, i)
                    logger.info("Validate at Epoch {} : {:.6f}".format(i, val_loss))

                    if visualize:
                        png_path = os.path.join(res_path, "png_training")
                        mkdir(png_path)
                        output_val, output_surface_val = normBackData(output_val, output_surface_val, aux_constants['weather_statistics_last'])
                        target_val, target_surface_val = normBackData(target_val, target_surface_val, aux_constants['weather_statistics_last'])
                        visuailze(output_val.detach().cpu().squeeze(), target_val.detach().cpu().squeeze(), input_val.detach().cpu().squeeze(), var='u', z=12, step=i, path=png_path)
                        visuailze_surface(output_surface_val.detach().cpu().squeeze(), target_surface_val.detach().cpu().squeeze(), input_surface_val.detach().cpu().squeeze(), var='msl', step=i, path=png_path)

                    if val_loss < best_loss:
                        best_loss = val_loss
                        torch.save(unwrap_model(model).state_dict(), os.path.join(model_save_path, 'best_model.pth'))
                        logger.info(f"current best model is saved at {i} epoch.")
                        epochs_since_last_improvement = 0
                    else:
                        epochs_since_last_improvement += 1
                        if epochs_since_last_improvement >= cfg.PG.TRAIN.EARLY_STOP:
                            logger.info(f"No improvement in validation loss for {epochs_since_last_improvement} epochs, terminating training.")
                            should_stop = True
                    del input_val, input_surface_val, target_val, target_surface_val, output_val, output_surface_val
                    torch.cuda.empty_cache()

        if is_dist_ready():
            stop_tensor = torch.tensor(1 if should_stop else 0, device=device)
            dist.broadcast(stop_tensor, src=0)
            should_stop = bool(stop_tensor.item())
        if should_stop:
            break

    return model

def str2bool(v):
    if isinstance(v, bool): return v
    if v.lower() in ('yes', 'true', 't', 'y', '1'): return True
    elif v.lower() in ('no', 'false', 'f', 'n', '0'): return False
    else: raise argparse.ArgumentTypeError('Boolean value expected.')

# =============================================================================
# 10. MAIN EXECUTION
# =============================================================================
if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('--data_root', type=str, default=os.environ.get('PANGU_DATA_ROOT', ''))
    parser.add_argument('--output_root', type=str, default='')
    parser.add_argument('--weights_path', type=str, default='')
    parser.add_argument('--type_net', type=str, default="finetune_fully")
    parser.add_argument('--load_pretrained', type=str2bool, default=False)
    parser.add_argument('--launcher', default='pytorch', help='job launcher')
    parser.add_argument('--local_rank', type=int, default=-1)
    parser.add_argument('--dist', type=str2bool, default=False)
    parser.add_argument('--only_test', type=str2bool, default=False)
    parser.add_argument('--visualize', type=str2bool, default=False)
    parser.add_argument('--only_use_wind_speed_loss', type=str2bool, default=False)
    parser.add_argument('--use_custom_mask', type=str2bool, default=False)
    parser.add_argument('--use_deepspeed', type=str2bool, default=False)
    parser.add_argument('--ds_config', type=str, default='')
    parser.add_argument('--backend', type=str, default='')
    parser.add_argument('--seed', type=int, default=cfg.GLOBAL.SEED)
    parser.add_argument('--deterministic', type=str2bool, default=False)
    args = parser.parse_args()

    if not args.data_root:
        raise ValueError('Missing --data_root (or PANGU_DATA_ROOT).')
    if not os.path.exists(args.data_root):
        raise FileNotFoundError(f"Data root not found: {args.data_root}")

    # Set Paths
    script_dir = os.path.dirname(os.path.abspath(__file__))
    cfg.PG_INPUT_PATH = args.data_root
    cfg.PG_OUT_PATH = args.output_root or os.path.join(args.data_root, 'model')
    custom_weights_path = args.weights_path or os.path.join(args.data_root, 'models', 'pangu_weather_24_torch.pth')

    set_random_seed(args.seed, deterministic=args.deterministic)
    
    torch.set_num_threads(cfg.GLOBAL.NUM_THREADS)

    # Distributed Setup
    dist_enabled = args.dist or args.use_deepspeed
    if args.use_deepspeed:
        import deepspeed
        deepspeed.init_distributed(dist_backend='nccl')
        rank, world_size = get_dist_info()
    elif args.dist:
        backend = _pick_backend(args.backend)
        init_dist(args.launcher, backend=backend)
        rank, world_size = get_dist_info()
    else:
        rank, world_size = 0, 1
    
    print(f"Rank: {rank}, World Size: {world_size}")
    
    if torch.cuda.is_available():
        if 'LOCAL_RANK' in os.environ:
            local_rank = int(os.environ['LOCAL_RANK'])
        elif args.local_rank >= 0:
            local_rank = args.local_rank
        else:
            local_rank = rank % max(1, torch.cuda.device_count())
        device = torch.device('cuda:' + str(local_rank))
    else:
        local_rank = 0
        device = torch.device('cpu')
    
    print(f"Predicting on {device}")

    output_path = os.path.join(cfg.PG_OUT_PATH, args.type_net, str(cfg.PG.HORIZON))
    mkdir(output_path)
    writer_path = os.path.join(output_path, "writer")
    mkdir(writer_path)
    writer = SummaryWriter(writer_path) if rank == 0 else None
    
    logger_name = args.type_net + str(cfg.PG.HORIZON)
    logger_info(logger_name, os.path.join(output_path, logger_name + '.log'))
    logger = logging.getLogger(logger_name)

    # Load Data
    train_dataset = NetCDFDataset(nc_path=cfg.PG_INPUT_PATH, training=True, validation=False, startDate=cfg.PG.TRAIN.START_TIME, endDate=cfg.PG.TRAIN.END_TIME, freq=cfg.PG.TRAIN.FREQUENCY, horizon=cfg.PG.HORIZON)
    
    train_sampler = None
    if dist_enabled:
        train_sampler = DistributedSampler(train_dataset, shuffle=True, drop_last=False)
        train_dataloader = data.DataLoader(
            dataset=train_dataset,
            batch_size=max(1, cfg.PG.TRAIN.BATCH_SIZE // world_size),
            drop_last=False,
            num_workers=4,
            pin_memory=True,
            persistent_workers=True,
            prefetch_factor=2,
            sampler=train_sampler,
        )
    else:
        train_dataloader = data.DataLoader(
            dataset=train_dataset,
            batch_size=max(1, cfg.PG.TRAIN.BATCH_SIZE),
            drop_last=False,
            shuffle=True,
            num_workers=4,
            pin_memory=True,
            persistent_workers=True,
            prefetch_factor=2,
        )

    val_dataset = NetCDFDataset(nc_path=cfg.PG_INPUT_PATH, training=False, validation=True,
                                startDate=cfg.PG.VAL.START_TIME, endDate=cfg.PG.VAL.END_TIME,
                                freq=cfg.PG.VAL.FREQUENCY, horizon=cfg.PG.HORIZON)
    val_dataloader = data.DataLoader(
        dataset=val_dataset,
        batch_size=max(1, cfg.PG.VAL.BATCH_SIZE),
        drop_last=False,
        shuffle=False,
        num_workers=2,
        pin_memory=True,
        persistent_workers=True,
        prefetch_factor=2,
    )

    # Load Model
    model = PanguModel(device=device).to(device)
    
    if os.path.exists(custom_weights_path):
        print(f"Loading weights from: {custom_weights_path}")
        weight_checkpoint = torch.load(custom_weights_path, map_location='cpu')
        load_model_state(model, weight_checkpoint)
    else:
        print(f"WARNING: Weights file not found at {custom_weights_path}. Initializing randomly.")

    for param in model.parameters():
        param.requires_grad = True

    if args.dist and not args.use_deepspeed:
        if torch.cuda.is_available():
            model = DDP(model, device_ids=[local_rank], output_device=local_rank)
        else:
            model = DDP(model)
        
    if args.use_deepspeed:
        parameters = filter(lambda p: p.requires_grad, model.parameters())
        ds_config = args.ds_config or os.path.join(script_dir, "ds_config.json")
        if not os.path.exists(ds_config):
            raise FileNotFoundError(f"DeepSpeed config not found: {ds_config}")
        model, optimizer, _, _ = deepspeed.initialize(args=args, model=model, model_parameters=parameters, config=ds_config)
        base_optimizer = model.optimizer.optimizer
        lr_scheduler = torch.optim.lr_scheduler.MultiStepLR(base_optimizer, milestones=[25, 50], gamma=0.5)
        start_epoch = 1
    else:
        optimizer = torch.optim.Adam(filter(lambda p: p.requires_grad, model.parameters()), lr=cfg.PG.TRAIN.LR, weight_decay=cfg.PG.TRAIN.WEIGHT_DECAY)
        lr_scheduler = torch.optim.lr_scheduler.MultiStepLR(optimizer, milestones=[25, 50], gamma=0.5)
        start_epoch = 1
        
    if args.load_pretrained:
        # Logic to resume training if needed
        prev_model_path = os.path.join(output_path, "models/train_34.pth") # Example
        if os.path.exists(prev_model_path):
            cpk = torch.load(prev_model_path, map_location=device)
            load_model_state(model, cpk, strict=False)
            if 'optimizer' in cpk: optimizer.load_state_dict(cpk['optimizer'])
            if 'lr_scheduler' in cpk: lr_scheduler.load_state_dict(cpk['lr_scheduler'])
            start_epoch = cpk["epoch"] + 1
            print(f"Resuming from epoch {start_epoch}")

    if not args.only_test:
        model = train(model, train_loader=train_dataloader, val_loader=val_dataloader,
                      optimizer=optimizer, lr_scheduler=lr_scheduler, res_path=output_path,
                      device=device, writer=writer, logger=logger, start_epoch=start_epoch, 
                      rank=rank, visualize=args.visualize, 
                      only_use_wind_speed_loss=args.only_use_wind_speed_loss, 
                      use_custom_mask=args.use_custom_mask, use_deepspeed=args.use_deepspeed,
                      train_sampler=train_sampler)